debug: False
###########
# Dataset #
###########
data_root: './data'
batch_size: 10
num_workers: 16
eval_batch_size: 256
eval_num_workers: 4
batch_iter: 1

num_tasks: 5
longtail: False
nb_classes: 10

multitask: False

#########
# Model #
#########

x_c: 1
x_h: 28
x_w: 28
y_c: 10

device: 'cuda'

d: 'mlp_classifier'
h1_dim: 64
h2_dim: 64

model_name: 'slab_rsvr' 
reservoir_name: 'random'
reservoir_size: 300
replay_multiple: 1 # replayed batch size relative to input size.

# Adaptive Replay batch
# Alter replay batch size buffer based on unique number of classes.
adaptive_replay: False

# Encoder Param
pretrained: False
fine_tune: True

# Corruption Parameters
corruption_list: [0,1,2,3,4,5,6,7,8,9]
corruption_percent: 0.2
asymmetric_noise: False

# only allow clean examples in reservoir
block_noise: False
mem_corruptness: 0.1

##################
# SCE parameters #
##################
SCE: False
alpha: 1.0
beta: 1.0

#########
# Train #
#########
weight_decay: 0.00001
implicit_lr_decay: False

#optimizer_d:
#  type: SGD
#  options:
#    lr: 0.01
#    momentum: 0.9

optimizer_d:
  type: Adam
  options:
    lr: 0.0002

lr_scheduler_d:
  type: MultiStepLR
  options:
    milestones: [1]
    gamma: 1.0

clip_grad:
  type: value
  options:
    clip_value: 0.5

########
# Eval #
########

eval: True

###########
# Summary #
###########

summary_step: 10
eval_step: 100
ckpt_step: 1000000000
summarize_samples: false

